---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: k8sdeploy
  name: k8sdeploy-agent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: k8sdeploy
  labels:
    name: agent
    app: agent
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
        name: agent
    spec:
      serviceAccountName: k8sdeploy-agent
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: agent
          image: containers.chewedfeed.com/k8sdeploy/agent:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: SERVICE_NAME
              value: agent

---
apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: k8sdeploy
  labels:
    app: agent
    name: agent
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
  selector:
    app: agent
