name: Pull Requests
on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: test
        run: go test -v -race -bench=./... -benchmem -timeout=120s -bench=./... ./...
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    needs:
      - test
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  k8sdeploy:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: k8sdeploy/github-action@v1
        with:
          service-name: agent
          service-namespace: k8sdeploy
          image-hash: ${{ github.sha }}
          image-tag: ${{ github.ref_name }}
          k8sdeploy-key: ${{ secrets.K8SDEPLOY_KEY }}
          k8sdeploy-secret: ${{ secrets.K8SDEPLOY_SECRET }}
          k8sdeploy-id: ${{ secrets.K8SDEPLOY_ID }}
